spring:

  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org:
      springframework.r2dbc: TRACE
      springframework.transaction: TRACE

read:
  datasource:
    driver: mysql
    host: localhost
    port: 3306
    database: WEBFLUX
    username: root
    password: 1234
write:
  datasource:
    driver: mysql
    host: localhost
    port: 3306
    database: WEBFLUX
    username: root
    password: 1234
