spring:
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false


logging:
  level:
    org:
      hibernate.type.descriptor.sql.BasicBinder: TRACE

webclient:
  h2-console-port: 8081
