spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/default
    username: root
    password: qwerqwer123
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false


logging:
  level:
    org:
      springframework.transaction: TRACE
      hibernate.type.descriptor.sql.BasicBinder: TRACE


read:
  datasource:
    #    url: r2dbc:mysql://localhost:3306/default
    #    username: root
    #    password: qwerqwer123
    driver: mysql
    host: localhost
    port: 3306
    database: default
    username: root
    password: qwerqwer123
write:
  datasource:
    #    url: r2dbc:mysql://localhost:3306/default
    driver: mysql
    host: localhost
    port: 3306
    database: default
    username: root
    password: qwerqwer123
